import{a as M,S as v,i as a}from"./assets/vendor-550cebad.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))h(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&h(f)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function h(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const C="43019622-51d65222f4845ee303d6eaf7d",H="https://pixabay.com/api/";async function g(t){try{return(await M.get(H,{params:{key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:"page",per_page:"perPage"}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const i=document.querySelector(".gallery"),y=new v(".gallery a",{captionsData:"alt",captionDelay:250});y.refresh();function L(t){i.innerHTML="",t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;i.insertAdjacentHTML("beforeend",s)}),y.refresh()}function E(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",i.insertAdjacentElement("afterend",t)}const P=document.querySelector(".form"),p=document.querySelector(".search-input"),w=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");m();let c="",n=1;const u=15;P.addEventListener("submit",S);async function S(t){if(t.preventDefault(),c=p.value.trim(),n=1,i.innerHTML="",c===""){a.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),l();return}$(),b();try{const e=await g(c,n,u),s=e.totalHits;if(e.hits.length===0){i.innerHTML="",a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),l();return}else L(e.hits),p.value="",q();u*n>=s&&(l(),E())}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{m()}}d.addEventListener("click",async()=>{try{d&&(n+=1);const t=await g(c,n,u),e=t.totalHits;L(t.hits),b(),u*n>=e&&(l(),E());const s=i.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),a.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{m()}});function b(){w.classList.remove("hidden")}function m(){w.classList.add("hidden")}function q(){d.style.display="block"}function l(){d.style.display="none"}function $(){const t=document.querySelector(".end-message");t&&t.remove()}
//# sourceMappingURL=commonHelpers.js.map
