import{a as b,S as M,i as a}from"./assets/vendor-550cebad.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))m(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&m(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function m(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const T="43019622-51d65222f4845ee303d6eaf7d",v="https://pixabay.com/api/";async function h(t){try{return(await b.get(v,{params:{key:T,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page,per_page:perPage}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const i=document.querySelector(".gallery"),g=new M(".gallery a",{captionsData:"alt",captionDelay:250});g.refresh();function y(t){i.innerHTML="",t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;i.insertAdjacentHTML("beforeend",s)}),g.refresh()}const C=document.querySelector(".form"),p=document.querySelector(".search-input"),L=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");let l="",n=1;const f=15;C.addEventListener("submit",H);async function H(t){if(t.preventDefault(),l=p.value.trim(),n=1,i.innerHTML="",l===""){a.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),c();return}S(),E();try{const e=await h(l,n,f),s=e.totalHits;if(e.hits.length===0){i.innerHTML="",a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),c();return}else y(e.hits),p.value="",P();f*n>=s&&(c(),showEndOfCollectionMessage())}catch(e){console.error("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{w()}}d.addEventListener("click",async()=>{try{d&&(n+=1);const t=await h(l,n,f),e=t.totalHits;y(t.hits),E(),f*n>=e&&(c(),showEndOfCollectionMessage());const s=i.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),a.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{w()}});function E(){L.classList.remove("hidden")}function w(){L.classList.add("hidden")}function P(){d.style.display="block"}function c(){d.style.display="none"}function S(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?scrollToTopBtn.style.display="flex":scrollToTopBtn.style.display="none"});
//# sourceMappingURL=commonHelpers.js.map
