import{a as T,S as b,i as l}from"./assets/vendor-550cebad.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))u(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&u(p)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const v="43019622-51d65222f4845ee303d6eaf7d",M="https://pixabay.com/api/";async function h(t){try{return(await T.get(M,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page,per_page:perPage}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const i=document.querySelector(".gallery"),g=new b(".gallery a",{captionsData:"alt",captionDelay:250});g.refresh();function y(t){i.innerHTML="",t.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;i.insertAdjacentHTML("beforeend",s)}),g.refresh()}const C=document.querySelector(".form"),m=document.querySelector(".search-input"),L=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");let a="",n=1;const f=15;C.addEventListener("submit",H);async function H(t){if(t.preventDefault(),a=m.value.trim(),n=1,i.innerHTML="",a===""){l.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),c();return}S(),w();try{const e=await h(a,n,f),s=e.totalHits;if(e.hits.length===0){i.innerHTML="",l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),c();return}else y(e.hits),m.value="",P();f*n>=s&&(c(),showEndOfCollectionMessage())}catch(e){console.error("Error fetching images:",e),l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{E()}}d.addEventListener("click",async()=>{try{d&&(n+=1);const t=await h(a,n,f),e=t.totalHits;y(t.hits),w(),f*n>=e&&(c(),showEndOfCollectionMessage());const s=i.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),l.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{E()}});function w(){L.classList.remove("hidden")}function E(){L.classList.add("hidden")}function P(){d.style.display="block"}function c(){d.style.display="none"}function S(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?scrollToTopBtn.style.display="flex":scrollToTopBtn.style.display="none"});function q(){window.scrollTo({top:0,behavior:"smooth"})}scrollToTopBtn.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
